docker-build:
  image: harbor.ulbricht.casa/proxy/library/docker:dind
  stage: build
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" harbor.ulbricht.casa
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker build --pull -t "harbor.ulbricht.casa/jinya/jinya-releases:${CI_COMMIT_TAG}" -f ./Dockerfile .
    - docker tag "harbor.ulbricht.casa/jinya/jinya-releases:${CI_COMMIT_TAG}" "harbor.ulbricht.casa/jinya/jinya-releases:latest"
    - docker tag "harbor.ulbricht.casa/jinya/jinya-releases:${CI_COMMIT_TAG}" "jinyacms/jinya-releases:${CI_COMMIT_TAG}"
    - docker tag "harbor.ulbricht.casa/jinya/jinya-releases:${CI_COMMIT_TAG}" jinyacms/jinya-releases:latest
    - docker push "harbor.ulbricht.casa/jinya/jinya-releases:${CI_COMMIT_TAG}"
    - docker push "harbor.ulbricht.casa/jinya/jinya-releases:latest"
    - docker push "jinyacms/jinya-releases:${CI_COMMIT_TAG}"
    - docker push "jinyacms/jinya-releases:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

build-merge-request:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: build
  script:
    - go vet
    - go build -o jinya-releases
