stages:
  - lint
  - test
  - build
  - deploy

lint:
  image: library/golang:1.22-alpine
  stage: lint
  script:
    - go vet

test:
  image: library/golang:1.22-alpine
  stage: test
  services:
    - name: library/postgres:14-alpine
      variables:
        POSTGRES_USER: jinya
        POSTGRES_PASSWORD: jinya
        POSTGRES_DB: jinya
  variables:
    DATABASE_URL: host=localhost port=5432 user=jinya password=jinya dbname=jinya
  script:
    - go test ./... -p 1

build:
  image: library/golang:1.22-alpine
  stage: build
  script:
    - go build -o jinya-releases

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}/${ARCH}:latest"
      --destination "jinyacms/jinya-releases:${CI_COMMIT_TAG}"
      --destination "jinyacms/jinya-releases:latest"
  rules:
    - if: $CI_COMMIT_TAG
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - runner-${ARCH}

merge-manifests:
  stage: deploy
  needs:
    - job: docker-build
      artifacts: false
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER}
      --password=${CI_REGISTRY_PASSWORD}
      push from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}/ARCH:${TAG}
      --target ${CI_REGISTRY_IMAGE}:${TAG}
  parallel:
    matrix:
      - TAG: latest
      - TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
