version: "3"
services:
  jinya-releases-postgres:
    image: library/postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jinya
      POSTGRES_PASSWORD: jinya
      POSTGRES_DB: jinya
    restart: always